name: virtual_mouse
description: "A package to simulate mouse events in Flutter"
version: 0.0.1
homepage: https://github.com/ayusuke7/virtual_mouse
repository: https://github.com/ayusuke7/virtual_mouse

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
