name: Dart Pub Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Get dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Publish package
        run: dart pub publish --force --non-interactive
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
